apiVersion: v2
name: ksm
description: A Helm chart for Kubernetes

type: application
version: 0.1.0

dependencies:
  - name: kube-state-metrics
    version: 2.13.2
    repository: https://kubernetes.github.io/kube-state-metrics
