apiVersion: v1
kind: Namespace
metadata:
  name: scraper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scraper
rules:
  - apiGroups: [""]
    resources:
      - "nodes"
      - "nodes/metrics"
      - "nodes/stats"
      - "nodes/proxy"
      - "pods"
      - "services"
    verbs: ["get", "list"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: scraper
  name: scraper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scraper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scraper
subjects:
  - kind: ServiceAccount
    name: scraper
    namespace: scraper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: scraper
spec:
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      serviceAccountName: scraper
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: alpine
          imagePullPolicy: IfNotPresent
          name: scraper
          command:
            - sh
          args:
            - -c
            - |
              apk add curl bash
              sleep 24h
          readinessProbe:
            exec:
              command:
                - which
                - bash
